name: gtep_flutter
description: A new Flutter starter project.
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  core:
    path: libraries/core
  cupertino_icons: ^1.0.2

  flutter:
    sdk: flutter

  auth:
    path: features/auth
  main:
    path: features/main
  settings:
    path: features/settings
  

  shared:
    path: libraries/shared

dev_dependencies:
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1
  very_good_analysis: ^3.0.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/flags/
    - assets/images/icons/
    - assets/images/illustrations/
    - assets/images/illustrations/onboarding/
    - assets/languages/
    - assets/maps/

  fonts:
    - family: 'Inter'
      fonts:
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
