name: settings
description: A new Flutter package project.
version: 0.0.1
homepage: none
publish_to: none

environment:
  sdk: '>=2.19.1 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  core:
    path: ../../libraries/core
  flutter:
    sdk: flutter
  shared:
    path: ../../libraries/shared
  auth:
    path: ../../features/auth

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1

flutter:
