// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  // static FirebaseOptions get currentPlatform {
  //   if (kIsWeb) {
  //     throw UnsupportedError(
  //       'DefaultFirebaseOptions have not been configured for web - '
  //       'you can reconfigure this by running the FlutterFire CLI again.',
  //     );
  //   }
  //   switch (defaultTargetPlatform) {
  //     case TargetPlatform.android:
  //       return android;
  //     case TargetPlatform.iOS:
  //       return ios;
  //     case TargetPlatform.macOS:
  //       throw UnsupportedError(
  //         'DefaultFirebaseOptions have not been configured for macos - '
  //         'you can reconfigure this by running the FlutterFire CLI again.',
  //       );
  //     case TargetPlatform.windows:
  //       throw UnsupportedError(
  //         'DefaultFirebaseOptions have not been configured for windows - '
  //         'you can reconfigure this by running the FlutterFire CLI again.',
  //       );
  //     case TargetPlatform.linux:
  //       throw UnsupportedError(
  //         'DefaultFirebaseOptions have not been configured for linux - '
  //         'you can reconfigure this by running the FlutterFire CLI again.',
  //       );
  //     default:
  //       throw UnsupportedError(
  //         'DefaultFirebaseOptions are not supported for this platform.',
  //       );
  //   }
  // }

  // static const FirebaseOptions android = FirebaseOptions(
  //   apiKey: 'AIzaSyCiShukkMSu5PgPXRdRpc5Wb6yBSvUJ-20',
  //   appId: '1:647761092600:android:068ef2badbd2aa86c0c00d',
  //   messagingSenderId: '647761092600',
  //   projectId: 'paos-taspen',
  //   storageBucket: 'paos-taspen.appspot.com',
  // );

  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyBUmZbUvaVzfIT78RcaG3EE2vZj0NtyEDI',
  //   appId: '1:647761092600:ios:b4af0b0c8afd50cec0c00d',
  //   messagingSenderId: '647761092600',
  //   projectId: 'paos-taspen',
  //   storageBucket: 'paos-taspen.appspot.com',
  //   iosBundleId: 'com.taspen.paos',
  // );
}
