name: shared
description: A new Flutter package project.
version: 0.0.1
homepage: none
publish_to: none

environment:
  sdk: '>=2.19.1 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  # libraries
  awesome_notifications: ^0.8.2
  core:
    path: ../core
  dartz: ^0.10.1
  dio: ^5.4.0
  dio_smart_retry: ^6.0.0
  # dots_indicator: ^3.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  #flutter_barcode_scanner: ^2.0.0
  flutter_bloc: ^8.1.5
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.10
  flutter_svg: ^2.0.9
  get_it: ^7.6.7
  go_router: ^13.0.1
  hive: ^2.2.3
  intl: ^0.19.0
  json_annotation: ^4.8.1
  keyboard_dismisser: ^3.0.0
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  #syncfusion_flutter_datepicker: ^25.2.7
  # table_calendar: ^3.0.9
  # sliding_up_panel: ^2.0.0+1
  # dotted_border: ^2.1.0
  # firebase_messaging: ^14.7.10
  # firebase_core: ^2.24.2
  #package_info_plus: ^5.0.1
  # webview_flutter: ^4.4.3
  # webview_flutter_wkwebview: ^3.10.1
  # device_info_plus: ^9.1.2
  permission_handler: ^11.3.1
  geolocator: ^11.0.0
  flutter_map: ^7.0.1
  flutter_map_mbtiles: ^1.0.3
  #mbtiles: ^0.4.2
  latlng: ^2.0.7


dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1

flutter:
  generate: true
